<?php

/**
 * @file
 * OEmbed field core hooks and functions
 */

/**
 * Implements hook_field_formatter_info().
 */
function oembedfield_field_formatter_info() {
  $formatters = array(
    'oembed_default' => array(
      'label' => t('OEmbed'),
      'field types' => array('link_field'),
      'description' => t('Embeds links if possible - otherwise just links them.'),
      'settings' => array('preset' => NULL),
    ),
  );

  return $formatters;
}

/**
 * Implements hook_field_formatter_settings_form().
 */
function oembedfield_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];

  $options = array(
    '' => t('default'),
  );
  foreach (oembedcore_preset_load_all() as $preset) {
    if (empty($preset->disabled)) {
      $options[$preset->name] = $preset->name;
    }
  }
  $element = array();
  $element['preset'] = array(
    '#title' => t('oEmbed preset'),
    '#type' => 'select',
    '#options' => $options,
    '#default_value' => $settings['preset'],
    '#required' => FALSE,
  );

  return $element;
}

/**
 * Implements hook_field_formatter_settings_summary().
 */
function oembedfield_field_formatter_settings_summary($field, $instance, $view_mode) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];

  $summary = '';

  $summary = t('Preset') . ': ' . (!empty($settings['preset']) ?  $settings['preset'] : 'default');

  return $summary;
}

/**
 * Implements hook_field_formatter_view().
 */
function oembedfield_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();

  foreach ($items as $delta => $item) {
    $attributes = array();
    $url = $item['url'];
    $preset = oembedcore_preset_load($display['settings']['preset']);
    if (!empty($preset)) {
      $attributes = array_filter(array(
        'maxwidth' => intval($preset->width),
        'maxheight' => intval($preset->height),
      ));
    }

    $element[$delta] = oembedcore_render_cache('oembed', $url, $attributes);
  }

  return $element;
}
