<?php

/**
 * @file
 * Provides a remote stream wrapper and file field integration.
 *
 * @todo Add a 'Remote URL' file field widget.
 */

/**
 * Stream wrapper type flag -- visible and readable using remote files that act like local files.
 */
define('STREAM_WRAPPERS_REMOTE', STREAM_WRAPPERS_LOCAL | STREAM_WRAPPERS_READ | STREAM_WRAPPERS_VISIBLE);

/**
 * Implements hook_menu().
 */
function remote_stream_wrapper_menu() {
  $items = array();

  // Add image style generation paths for external URLs.
  if (module_exists('image')) {
    $wrappers = file_get_remote_stream_wrappers();
    $directory_path = file_stream_wrapper_get_instance_by_scheme(file_default_scheme())->getDirectoryPath();
    $pos = count(explode('/', $directory_path)) + 1;
    $item = array(
      'page callback' => 'remote_stream_wrapper_image_style_deliver',
      'page arguments' => array($pos, $pos + 1),
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
      'file' => 'remote_stream_wrapper.image.inc',
    );
    foreach (array_keys($wrappers) as $scheme) {
      $items[$directory_path . '/styles/%image_style/' . $scheme] = $item;
    }
  }

  return $items;
}

/**
 * Implements hook_permission().
 */
function remote_stream_wrapper_permission() {
  $permission = array();

  if (module_exists('media')) {
    $permission['add media from remote urls'] = array(
      'title' => t('Add media from remote URLs'),
      'description' => t('Add media from remote URLs.'),
    );
  }

  return $permission;
}

/**
 * Implements hook_stream_wrappers().
 */
function remote_stream_wrapper_stream_wrappers() {
  $info['http'] = array(
    'name' => t('HTTP URLs'),
    'class' => 'DrupalRemoteStreamWrapper',
    'description' => t('Remote files.'),
    'type' => STREAM_WRAPPERS_REMOTE,
    'remote' => TRUE,
  );
  $info['https'] = $info['http'];
  $info['https']['name'] = t('HTTPS URLs');
  $info['feed'] = $info['http'];
  $info['feed']['name'] = t('Feed URLs');

  return $info;
}

/**
 * Return a list of remote stream wrappers.
 */
function file_get_remote_stream_wrappers() {
  $wrappers = file_get_stream_wrappers(STREAM_WRAPPERS_REMOTE);
  foreach ($wrappers as $scheme => $wrapper) {
    if (empty($wrapper['remote'])) {
      unset($wrappers[$scheme]);
    }
  }
  //$wrappers = array_diff_key($wrappers, file_get_stream_wrappers(STREAM_WRAPPERS_LOCAL_NORMAL));
  return $wrappers;
}

/**
 * Check if a stream wrapper scheme is a remote stream wrapper.
 */
function file_is_scheme_remote($scheme) {
  $wrappers = file_get_remote_stream_wrappers();
  return isset($wrappers[$scheme]);
}

/**
 * Implements hook_process_image_style().
 */
function remote_stream_wrapper_process_image_style(&$variables) {
  $variables['source_path'] = $variables['path'];
}

/**
 * Implements hook_preprocess_image().
 */
function remote_stream_wrapper_preprocess_image(&$variables) {
  if (!empty($variables['style_name']) && !empty($variables['source_path'])) {
    $uri = $variables['source_path'];
    if (file_is_scheme_remote(file_uri_scheme($uri))) {
      $variables['path'] = remote_stream_wrapper_image_style_path($variables['style_name'], $uri);
    }
  }
}

/**
 * Copy of image_style_path() for use with remote images.
 *
 * When image_style_path() is give a file like 'http://example.com/image.png'
 * it is converted into 'http://styles/stylename/http/example.com/image.png'
 * which will fail image_style_deliver().
 */
function remote_stream_wrapper_image_style_path($style_name, $uri) {
  $scheme = file_uri_scheme($uri);
  $host = parse_url($uri, PHP_URL_HOST);

  // Retrieve the canonical extension of the file. If it's not an image, then
  // generating an image style is unlikely to work, so return the source URL.
  $extension = remote_stream_wrapper_image_style_extension($uri);
  if (!isset($extension)) {
    return $uri;
  }

  // The remote URL might have a query string or other characters that we don't
  // want in the generated derivative filename, so use a hash for the derivative
  // name.
  $hash = hash('sha256', $uri);

  // Add this URL to the database, so that
  // remote_stream_wrapper_image_style_deliver() knows that this is an allowed
  // file to fetch and process, and can recover the source URL from the hash.
  db_merge('remote_stream_wrapper_url')
    ->key(array('id' => $hash))
    ->fields(array('url' => $uri))
    ->execute();

  // Place the derivative in the default file scheme.
  return file_default_scheme() . '://styles/' . $style_name . '/' . $scheme . '/' . $host . '/' . $hash . '.' . $extension;
}

/**
 * Returns the canonical extension for the mimetype of the URI, if it's an image.
 */
function remote_stream_wrapper_image_style_extension($uri) {
  $mimetype = file_get_mimetype($uri);
  if (strpos($mimetype, 'image/') === 0) {
    include_once DRUPAL_ROOT . '/includes/file.mimetypes.inc';
    $mapping = file_mimetype_mapping();
    $mimetypes = array_flip($mapping['mimetypes']);
    $extensions = array_flip($mapping['extensions']);
    if (isset($mimetypes[$mimetype]) && isset($extensions[$mimetypes[$mimetype]])) {
      return $extensions[$mimetypes[$mimetype]];
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Manually add support for the remote stream wrapper in file fields since
 * it is read-only.
 */
function remote_stream_wrapper_form_field_ui_field_edit_form_alter(&$form, &$form_state) {
  if ($form['#field']['type'] == 'file' || $form['#field']['type'] == 'image') {
    $form['field']['settings']['uri_scheme']['#description'] .= ' ' . t('This only applies to uploaded files and not remote files.');
  }
}

/**
 * Validation callback for remote URLs.
 */
function remote_stream_wrapper_validate_url($element, &$form_state) {
  $value = $element['#value'];
  if ($value != '' && !valid_url($value, TRUE)) {
    form_error($element, t('Invalid URL %url.', array('%url' => $value)));
  }
  elseif (!file_stream_wrapper_valid_scheme(file_uri_scheme($value))) {
    // Check that the scheme is supported.
    form_error($element, t('Remote URLs with the %scheme scheme are not supported.', array('%scheme' => $scheme)));
  }
  else {
    // Check that the file exists.
    $request = drupal_http_request($value, array('method' => 'HEAD'));
    if (!empty($request->error)) {
      form_error($element, t('Unable to fetch file from URL %url (error @code: %error).', array('%url' => $value, '@code' => $request->code, '%error' => $request->error)));
    }
  }
}

/**
 * Load a file object by URI.
 *
 * @param string $uri
 *   A string containing the URI, path, or filename.
 *
 * @return
 *   A file object, or FALSE if not found.
 */
function remote_stream_wrapper_file_load_by_uri($uri) {
  $uri = file_stream_wrapper_uri_normalize($uri);
  $files = entity_load('file', FALSE, array('uri' => $uri));
  return !empty($files) ? reset($files) : FALSE;
}

/**
 * Helper functon to assemble a new file entity object by URI.
 *
 * @param string $uri
 *   A string containing the URI, path, or filename.
 */
function remote_stream_wrapper_file_create_by_uri($uri) {
  $uri = file_stream_wrapper_uri_normalize($uri);

  $file = new stdClass();
  $file->fid = NULL;
  $file->uri = $uri;
  $file->filename = basename($file->uri);
  $file->filemime = file_get_mimetype($file->uri);
  $file->uid = $GLOBALS['user']->uid;
  $file->status = FILE_STATUS_PERMANENT;
  file_save($file);
  return $file;
}

/**
 * Implements hook_media_browser_plugin_info().
 */
function remote_stream_wrapper_media_browser_plugin_info() {
  $plugins = array();
  // This depends on media_internet being enabled.
  if (user_access('administer media') || user_access('add media from remote urls')) {
    $plugins['remote_file'] = array(
      '#title' => t('Remote URL'),
      '#weight' => -10,
    );
  }
  return $plugins;
}

/**
 * Implements hook_media_browser_plugin_view().
 */
function remote_stream_wrapper_media_browser_plugin_view($plugin_name, $params) {
  $path = drupal_get_path('module', 'media');

  $types = isset($params['types']) ? $params['types'] : array();

  $redirect = array('media/browser', array('query' => array('render' => 'media-popup')));
  switch ($plugin_name) {
    case 'remote_file':
      // @todo: implement the multiselect argument here.
      $from_web_form = drupal_get_form('remote_stream_wrapper_media_browser_form', $types);
      return array(
        '#title' => t('Remote URL'),
        'form' => array($from_web_form),
      );
      break;
  }

  return array();
}

/**
 * Provides a form for adding media items from remote URLs.
 *
 * @see remote_stream_wrapper_media_browser_form_submit()
 */
function remote_stream_wrapper_media_browser_form($form, &$form_state = array(), $types = array()) {
  $form['url'] = array(
    '#type' => 'textfield',
    '#title' => 'URL',
    '#attributes' => array('class' => array('media-add-from-remote-url')),
    '#maxlength' => 255, // Maximum length of {file_managed}.uri
    '#element_validate' => array('remote_stream_wrapper_validate_url'),
    '#required' => TRUE,
    '#file_types' => $types,
  );

  // @todo Validate against file field allowed types.
  $form['#validators'] = array();
  if ($types) {
    //$form['#validators']['media_file_validate_types'] = array($types);
  }

  $form['actions'] = array('#type' => 'actions');
  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );
  return $form;
}

/**
 * Save a file record based on a remote URL.
 *
 * @see remote_stream_wrapper_media_browser_form()
 * @see file_save()
 * @see DrupalRemoteStreamWrapper
 */
function remote_stream_wrapper_media_browser_form_submit($form, &$form_state) {
  $uri = $url = $form_state['values']['url'];

  try {
    $file = remote_stream_wrapper_file_load_by_uri($uri);
    if (!$file) {
      $file = remote_stream_wrapper_file_create_by_uri($uri);
    }
  }
  catch (Exception $e) {
    form_set_error('url', $e->getMessage());
    return;
  }

  if (empty($file->fid)) {
    form_set_error('url', t('Unable to add file from URL %file.', array('%file' => $url)));
    return;
  }

  $form_state['redirect'] = array('media/browser', array('query' => array('render' => 'media-popup', 'fid' => $file->fid)));
}
